package contract

import (
        "net/http"

        "github.com/Ammar777782439/mujeeb24-backend-go/internal/adapters/primary/http/dto"
        "github.com/danielgtaylor/huma/v2"
)

var platformSecurity = []map[string][]string{{"bearerAuth": {}}}

var platformErrors = []int{
        http.StatusBadRequest,
        http.StatusForbidden,
        http.StatusNotFound,
        http.StatusConflict,
        http.StatusUnprocessableEntity,
        http.StatusInternalServerError,
}

func registerPlatformOperations(api huma.API, dispatcher DashboardOperationHandler) {
        // ---- Plan Management (Contract §19) ----
        register(api, dispatcher, huma.Operation{OperationID: "platformCreatePlan", Method: http.MethodPost, Path: "/platform/plans", Tags: []string{"Platform.Plans"}, Summary: "Create a new plan (DRAFT).", Security: platformSecurity, DefaultStatus: http.StatusCreated, Errors: platformErrors}, dto.CreatePlanInput{}, Single[dto.PlanView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformListPlans", Method: http.MethodGet, Path: "/platform/plans", Tags: []string{"Platform.Plans"}, Summary: "List plans.", Security: platformSecurity, Errors: platformErrors}, dto.PlanListInput{}, List[dto.PlanView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetPlan", Method: http.MethodGet, Path: "/platform/plans/{plan_id}", Tags: []string{"Platform.Plans"}, Summary: "Get a plan.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformPlanPath{}, Single[dto.PlanView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformActivatePlan", Method: http.MethodPost, Path: "/platform/plans/{plan_id}/activate", Tags: []string{"Platform.Plans"}, Summary: "Activate a DRAFT plan.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.PlanActivateInput{}, Single[dto.PlanView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformRetirePlan", Method: http.MethodPost, Path: "/platform/plans/{plan_id}/retire", Tags: []string{"Platform.Plans"}, Summary: "Retire an ACTIVE plan.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.PlanRetireInput{}, Single[dto.PlanView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformCreatePlanVersion", Method: http.MethodPost, Path: "/platform/plans/{plan_id}/versions", Tags: []string{"Platform.Plans"}, Summary: "Create a new plan version.", Security: platformSecurity, DefaultStatus: http.StatusCreated, Errors: platformErrors}, dto.CreatePlanVersionInput{}, Single[dto.PlanView]{})

        // ---- Business Management (Contract §13-14) ----
        register(api, dispatcher, huma.Operation{OperationID: "platformCreateBusiness", Method: http.MethodPost, Path: "/platform/businesses", Tags: []string{"Platform.Businesses"}, Summary: "Create a new business (status=pending_setup). Per Contract §9, §13.", Security: platformSecurity, DefaultStatus: http.StatusCreated, Errors: platformErrors}, dto.CreateBusinessInput{}, Single[dto.PlatformBusinessView]{})

        register(api, dispatcher, huma.Operation{OperationID: "platformListBusinesses", Method: http.MethodGet, Path: "/platform/businesses", Tags: []string{"Platform.Businesses"}, Summary: "List businesses.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformBusinessListInput{}, List[dto.PlatformBusinessView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetBusiness", Method: http.MethodGet, Path: "/platform/businesses/{business_id}", Tags: []string{"Platform.Businesses"}, Summary: "Get a business.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformBusinessPath{}, Single[dto.PlatformBusinessView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformSuspendBusiness", Method: http.MethodPost, Path: "/platform/businesses/{business_id}/suspend", Tags: []string{"Platform.Businesses"}, Summary: "Suspend a business.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.PlatformBusinessSuspendInput{}, Single[dto.PlatformBusinessView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformReactivateBusiness", Method: http.MethodPost, Path: "/platform/businesses/{business_id}/reactivate", Tags: []string{"Platform.Businesses"}, Summary: "Reactivate a business.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.PlatformBusinessReactivateInput{}, Single[dto.PlatformBusinessView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformArchiveBusiness", Method: http.MethodPost, Path: "/platform/businesses/{business_id}/archive", Tags: []string{"Platform.Businesses"}, Summary: "Archive a business.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.PlatformBusinessArchiveInput{}, Single[dto.PlatformBusinessView]{})

        // ---- Platform Audit (Contract §49) ----
        register(api, dispatcher, huma.Operation{OperationID: "platformListAuditEvents", Method: http.MethodGet, Path: "/platform/audit-events", Tags: []string{"Platform.Audit"}, Summary: "List platform audit events.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformAuditListInput{}, List[dto.PlatformAuditEventView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetAuditEvent", Method: http.MethodGet, Path: "/platform/audit-events/{event_id}", Tags: []string{"Platform.Audit"}, Summary: "Get a platform audit event.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformAuditEventPathInput{}, Single[dto.PlatformAuditEventView]{})

        // ---- AI Operations (Contract §75-108, §85, §107) ----
        register(api, dispatcher, huma.Operation{OperationID: "platformGetAIOverview", Method: http.MethodGet, Path: "/platform/ai", Tags: []string{"Platform.AI"}, Summary: "AI runtime + provider overview.", Security: platformSecurity, Errors: platformErrors}, dto.EmptyInput{}, Single[dto.PlatformAIOverviewView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformAIDisable", Method: http.MethodPost, Path: "/platform/ai/disable", Tags: []string{"Platform.AI"}, Summary: "AI Emergency Kill Switch.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.PlatformAIRuntimeDisableInput{}, Single[dto.PlatformAIOverviewView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformAIEnable", Method: http.MethodPost, Path: "/platform/ai/enable", Tags: []string{"Platform.AI"}, Summary: "Re-enable AI Runtime.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.PlatformAIRuntimeEnableInput{}, Single[dto.PlatformAIOverviewView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformAIHealthCheck", Method: http.MethodPost, Path: "/platform/ai/health-check", Tags: []string{"Platform.AI"}, Summary: "AI health check.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.PlatformAIHealthCheckInput{}, Single[dto.PlatformAIHealthCheckResult]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformListAIProviders", Method: http.MethodGet, Path: "/platform/ai/providers", Tags: []string{"Platform.AI"}, Summary: "List AI providers.", Security: platformSecurity, Errors: platformErrors}, dto.EmptyInput{}, List[dto.PlatformProviderView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetAIProvider", Method: http.MethodGet, Path: "/platform/ai/providers/{provider_id}", Tags: []string{"Platform.AI"}, Summary: "Get a single AI provider.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformProviderPathInput{}, Single[dto.PlatformProviderView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetAIUsageOverview", Method: http.MethodGet, Path: "/platform/ai/usage", Tags: []string{"Platform.AI"}, Summary: "Platform-wide AI usage aggregate.", Security: platformSecurity, Errors: platformErrors}, dto.EmptyInput{}, Single[dto.PlatformAIUsageOverviewView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetAIUsageBySubscription", Method: http.MethodGet, Path: "/platform/ai/usage/by-subscription", Tags: []string{"Platform.AI"}, Summary: "AI usage by subscription.", Security: platformSecurity, Errors: platformErrors}, dto.SubscriptionListInput{}, List[dto.SubscriptionAIUsageView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetAIUsageByBusiness", Method: http.MethodGet, Path: "/platform/ai/usage/by-business", Tags: []string{"Platform.AI"}, Summary: "AI usage by business.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformBusinessListInput{}, List[dto.BusinessAIUsageView]{})

        // ---- Subscription Lifecycle (Contract §20-36) ----
        register(api, dispatcher, huma.Operation{OperationID: "platformListSubscriptions", Method: http.MethodGet, Path: "/platform/subscriptions", Tags: []string{"Platform.Subscriptions"}, Summary: "List subscriptions.", Security: platformSecurity, Errors: platformErrors}, dto.SubscriptionListInput{}, List[dto.SubscriptionView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetSubscription", Method: http.MethodGet, Path: "/platform/subscriptions/{subscription_id}", Tags: []string{"Platform.Subscriptions"}, Summary: "Get a subscription.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformSubscriptionPath{}, Single[dto.SubscriptionView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformCreateSubscription", Method: http.MethodPost, Path: "/platform/businesses/{business_id}/subscriptions", Tags: []string{"Platform.Subscriptions"}, Summary: "Create a subscription.", Security: platformSecurity, DefaultStatus: http.StatusCreated, Errors: platformErrors}, dto.CreateSubscriptionInput{}, Single[dto.SubscriptionView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformCancelSubscription", Method: http.MethodPost, Path: "/platform/subscriptions/{subscription_id}/cancel", Tags: []string{"Platform.Subscriptions"}, Summary: "Cancel a subscription.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.CancelSubscriptionInput{}, Single[dto.SubscriptionView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetSubscriptionAIUsage", Method: http.MethodGet, Path: "/platform/subscriptions/{subscription_id}/ai-usage", Tags: []string{"Platform.Subscriptions"}, Summary: "Get subscription AI usage.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformSubscriptionPath{}, Single[dto.SubscriptionAIUsageView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformOverrideSubscriptionAICostBudget", Method: http.MethodPost, Path: "/platform/subscriptions/{subscription_id}/ai-cost-budget", Tags: []string{"Platform.Subscriptions"}, Summary: "Override subscription cost budget.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.SubscriptionAICostBudgetOverrideInput{}, Single[dto.SubscriptionAIUsageView]{})

        // ---- Manual Payment Recording (Contract §25-28) ----
        register(api, dispatcher, huma.Operation{OperationID: "platformRecordPayment", Method: http.MethodPost, Path: "/platform/subscriptions/{subscription_id}/payments", Tags: []string{"Platform.Payments"}, Summary: "Record a manual payment.", Security: platformSecurity, DefaultStatus: http.StatusCreated, Errors: platformErrors}, dto.RecordPaymentInput{}, Single[dto.PaymentView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformListPayments", Method: http.MethodGet, Path: "/platform/subscriptions/{subscription_id}/payments", Tags: []string{"Platform.Payments"}, Summary: "List payments.", Security: platformSecurity, Errors: platformErrors}, dto.PaymentListInput{}, List[dto.PaymentView]{})

        // ---- Support Management (Contract §37-44) ----
        register(api, dispatcher, huma.Operation{OperationID: "platformCreateSupportTicket", Method: http.MethodPost, Path: "/platform/businesses/{business_id}/support/tickets", Tags: []string{"Platform.Support"}, Summary: "Create a support ticket.", Security: platformSecurity, DefaultStatus: http.StatusCreated, Errors: platformErrors}, dto.CreateSupportTicketInput{}, Single[dto.SupportTicketView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformListSupportTickets", Method: http.MethodGet, Path: "/platform/support/tickets", Tags: []string{"Platform.Support"}, Summary: "List support tickets.", Security: platformSecurity, Errors: platformErrors}, dto.SupportTicketListInput{}, List[dto.SupportTicketView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetSupportTicket", Method: http.MethodGet, Path: "/platform/support/tickets/{ticket_id}", Tags: []string{"Platform.Support"}, Summary: "Get a support ticket.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformSupportTicketPath{}, Single[dto.SupportTicketView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformCreateSupportMessage", Method: http.MethodPost, Path: "/platform/support/tickets/{ticket_id}/messages", Tags: []string{"Platform.Support"}, Summary: "Append a message to a ticket.", Security: platformSecurity, DefaultStatus: http.StatusCreated, Errors: platformErrors}, dto.CreateSupportMessageInput{}, Single[dto.SupportMessageView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformStartSupportTicket", Method: http.MethodPost, Path: "/platform/support/tickets/{ticket_id}/start", Tags: []string{"Platform.Support"}, Summary: "Start working on a ticket.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.StartSupportTicketInput{}, Single[dto.SupportTicketView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformResolveSupportTicket", Method: http.MethodPost, Path: "/platform/support/tickets/{ticket_id}/resolve", Tags: []string{"Platform.Support"}, Summary: "Resolve a ticket.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.ResolveSupportTicketInput{}, Single[dto.SupportTicketView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformCloseSupportTicket", Method: http.MethodPost, Path: "/platform/support/tickets/{ticket_id}/close", Tags: []string{"Platform.Support"}, Summary: "Close a resolved ticket.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.CloseSupportTicketInput{}, Single[dto.SupportTicketView]{})

        // ---- Channel Operations (Contract §89-96, §107) ----
        register(api, dispatcher, huma.Operation{OperationID: "platformListChannels", Method: http.MethodGet, Path: "/platform/channels", Tags: []string{"Platform.Channels"}, Summary: "List all channel connections.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformChannelListInput{}, List[dto.PlatformChannelView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetChannel", Method: http.MethodGet, Path: "/platform/channels/{connection_id}", Tags: []string{"Platform.Channels"}, Summary: "Get a channel connection.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformChannelPathInput{}, Single[dto.PlatformChannelView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformChannelHealthCheck", Method: http.MethodPost, Path: "/platform/channels/{connection_id}/health-check", Tags: []string{"Platform.Channels"}, Summary: "Run channel health check.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.PlatformChannelHealthCheckInput{}, Single[dto.PlatformChannelView]{})

        // ---- Provider Operations (Contract §97-98, §107) ----
        register(api, dispatcher, huma.Operation{OperationID: "platformListProviders", Method: http.MethodGet, Path: "/platform/providers", Tags: []string{"Platform.Providers"}, Summary: "List all external providers.", Security: platformSecurity, Errors: platformErrors}, dto.EmptyInput{}, List[dto.PlatformProviderView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetProvider", Method: http.MethodGet, Path: "/platform/providers/{provider_id}", Tags: []string{"Platform.Providers"}, Summary: "Get a single provider.", Security: platformSecurity, Errors: platformErrors}, dto.PlatformProviderPathInput{}, Single[dto.PlatformProviderView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformProviderHealthCheck", Method: http.MethodPost, Path: "/platform/providers/{provider_id}/health-check", Tags: []string{"Platform.Providers"}, Summary: "Run provider health check.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.PlatformProviderHealthCheckInput{}, Single[dto.PlatformProviderView]{})

        // ---- AI Provider Configuration (§13) ----
        register(api, dispatcher, huma.Operation{OperationID: "platformListAIProvidersConfig", Method: http.MethodGet, Path: "/platform/operations/ai/providers", Tags: []string{"Platform.AIConfig"}, Summary: "List AI providers with credential status.", Security: platformSecurity, Errors: platformErrors}, dto.EmptyInput{}, List[dto.AICredentialView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformAddAICredential", Method: http.MethodPost, Path: "/platform/operations/ai/providers/{provider}/credentials", Tags: []string{"Platform.AIConfig"}, Summary: "Add/rotate AI provider credential.", Security: platformSecurity, DefaultStatus: http.StatusCreated, Errors: platformErrors}, dto.AddCredentialInput{}, Single[dto.AICredentialView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformTestAIConnection", Method: http.MethodPost, Path: "/platform/operations/ai/providers/{provider}/test", Tags: []string{"Platform.AIConfig"}, Summary: "Test AI provider connection.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.TestConnectionInput{}, Single[dto.TestConnectionResult]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformDiscoverAIModels", Method: http.MethodPost, Path: "/platform/operations/ai/providers/{provider}/models", Tags: []string{"Platform.AIConfig"}, Summary: "Discover available models from provider.", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.DiscoverModelsInput{}, List[dto.AIModelView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformGetAIConfiguration", Method: http.MethodGet, Path: "/platform/operations/ai/configuration", Tags: []string{"Platform.AIConfig"}, Summary: "Get current active AI configuration.", Security: platformSecurity, Errors: platformErrors}, dto.EmptyInput{}, Single[dto.AIConfigurationView]{})
        register(api, dispatcher, huma.Operation{OperationID: "platformUpdateAIConfiguration", Method: http.MethodPut, Path: "/platform/operations/ai/configuration", Tags: []string{"Platform.AIConfig"}, Summary: "Update active AI configuration (model, limits).", Security: platformSecurity, DefaultStatus: http.StatusOK, Errors: platformErrors}, dto.UpdateConfigurationInput{}, Single[dto.AIConfigurationView]{})
}

func init() { _ = registerPlatformOperations }
